// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://socykdrfxerwjuscvkdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvY3lrZHJmeGVyd2p1c2N2a2RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NDk3NzIsImV4cCI6MjA2NTEyNTc3Mn0.r1j7KR41d439G6gkWp74NI-tjHXFvyaSr6xrZhc7MzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);